# Generated by Django 4.2 on 2025-09-06 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('sent_date', models.DateTimeField()),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Neutral', max_length=20)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Not urgent', 'Not urgent')], default='Not urgent', max_length=20)),
                ('contact_info', models.TextField(blank=True)),
                ('request_summary', models.TextField(blank=True)),
                ('ai_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_emails', models.IntegerField(default=0)),
                ('urgent_emails', models.IntegerField(default=0)),
                ('positive_sentiment', models.IntegerField(default=0)),
                ('negative_sentiment', models.IntegerField(default=0)),
                ('neutral_sentiment', models.IntegerField(default=0)),
                ('resolved_emails', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
